---
#- include_vars: credentials.yml
#- debug:
#    msg: "{{secret_mysql_user_password}}"
- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ deb_mysql_install_packages is defined and deb_mysql_install_packages.changed }}"

- name: Update apt cache
  apt: 
    update_cache: yes 
    cache_valid_time: 86400
  changed_when: false

- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: present

- name: Install mariadb
  apt:
    name: mariadb-server
    state: present
    install_recommends: yes 
  when: mariadb 

   # Configure MySQL.
- include_tasks: configure.yml
- include_tasks: secure-installation.yml
- include_tasks: databases.yml
- include_tasks: users.yml