---
webserver_stable_os:
  - CentOS 7
  - CentOS 8
  - Debian 9
  - Debian 10
  - Fedora 30
  - Fedora 31
  - Fedora 32
  - Fedora 33
  - Fedora 34
  - openSUSE Leap 15
  - openSUSE Leap 42
  - Ubuntu 16
  - Ubuntu 18  - Ubuntu 20

webserver_name: []
webserver_user: []
webserver_conf_file: []
