samba_prerequirements:
- samba
- samba-common
samba_workgroup: WORKGROUP
samba_security: user
samba_server_role: standalone server
samba_share_path: /media/
samba_groups:
  []
samba_shares:
  []
samba_users:
  []