---

- name: Copy dynu.sh
  template:
    src: dynu.sh.j2
    dest: /usr/local/bin/dynu.sh
    owner: wiaf
    group: users
    mode: 0700

 - name: Cron Job
  cron:
    name: synch with dynuwdns
    minute: '5'
    hour: '*'
    weekday: '*'
    user: wiaf
    job: /usr/local/bin/dynu.sh
    cron_file: dynu
    state: present