---
# Pass in a comma-separated list of repos to use (e.g. "remi,epel"). Used only
# for RHEL/CentOS.
php_enablerepo: ""

# Extra packages to install (in addition to distro-specific default lists).
php_packages_extra: []

# Default PHP version to install on Debian-based OSes (OS-specific).
# php_default_version_debian: ""

# PHP package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
php_packages_state: present

# Whether to install recommended packages. Used only for Debian/Ubuntu.
php_install_recommends: true

# Set this to false if you're not using PHP with Apache/Nginx/etc.
php_enable_webserver: true

# PHP-FPM configuration.
php_enable_php_fpm: false
php_fpm_state: started
php_fpm_handler_state: restarted
php_fpm_enabled_on_boot: true
php_fpm_listen: "127.0.0.1:9000"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 50
php_fpm_pm_start_servers: 5
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 5
php_fpm_pm_max_requests: 0

# PHP-FPM pool configuration.
php_fpm_pools:
  - pool_name: www
    pool_template: www.conf.j2
    pool_listen: "{{ php_fpm_listen }}"
    pool_listen_allowed_clients: "{{ php_fpm_listen_allowed_clients }}"
    pool_pm: dynamic
    pool_pm_max_children: "{{ php_fpm_pm_max_children }}"
    pool_pm_start_servers: "{{ php_fpm_pm_start_servers }}"
    pool_pm_min_spare_servers: "{{ php_fpm_pm_min_spare_servers }}"
    pool_pm_max_spare_servers: "{{ php_fpm_pm_max_spare_servers }}"
    pool_php_fpm_pm_max_requests: "{{ php_fpm_pm_max_requests }}"

# The executable to run when calling PHP from the command line.
php_executable: "php"

# OpCache settings.
php_opcache_zend_extension: "opcache.so"
php_opcache_enable: "1"
php_opcache_enable_cli: "0"
php_opcache_memory_consumption: "96"
php_opcache_interned_strings_buffer: "16"
php_opcache_max_accelerated_files: "4096"
php_opcache_max_wasted_percentage: "5"
php_opcache_validate_timestamps: "1"
php_opcache_revalidate_path: "0"
php_opcache_revalidate_freq: "2"
php_opcache_max_file_size: "0"
php_opcache_blacklist_filename: ""

# APCu settings.
php_enable_apc: true
php_apc_shm_size: "96M"
php_apc_enable_cli: "0"