---
- name: Update nginx confs for WordPress + PHP
  template:
    src: ../templates/default-site.conf
    dest: /etc/nginx/sites-available/{{server_hostname}}
    owner: www-data
    group: www-data
    mode: 0644
  become: yes
  notify:
    - restart nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/{{server_hostname}}
    dest: /etc/nginx/sites-enabled/{{server_hostname}}
    owner: www-data
    group: www-data
    state: link
  become: yes
  notify:
    - restart nginx
