---
- name: Check if youtube-dl is already installed
  stat:
    path: "{{ youtubedl_executable_path }}"
  register: youtubedl_bin

- name: Download from source move to executables folder and set permissions
  get_url:
    url: http://yt-dl.org/latest/youtube-dl
    dest: "{{ youtubedl_executable_path }}"
    mode: 0755
    force: yes
  when: not youtubedl_bin.stat.exists

- name: Update youtube-dl
  command: youtube-dl -U
  register: youtubedl_update_out
  when: youtubedl_bin.stat.exists and youtubedl_update
  changed_when: "'Updated youtube-dl.' in youtubedl_update_out.stdout"
  failed_when: "'ERROR:' in youtubedl_update_out.stdout"
  ignore_errors: true

- name: Copy soundload.sh
  copy:
    src: soundload.sh
    dest: /usr/local/bin/soundload.sh
    owner: root
    group: root
    mode: 0755

- name: Cron Job
  cron:
    name: Add date and time to a file.
    minute: '0'
    hour: '*'
    weekday: '*'
    user: wiaf
    job: /usr/local/bin/soundload.sh
    cron_file: soundload
    state: present
