---
- name: Check if youtube-dl is already installed
  stat:
    path: "{{ youtubedl_executable_path }}"
  register: youtubedl_bin

- name: Download from source move to executables folder and set permissions
  get_url:
    url: http://yt-dl.org/latest/youtube-dl
    dest: "{{ youtubedl_executable_path }}"
    mode: 0755
    force: yes
  when: not youtubedl_bin.stat.exists

- name: Update youtube-dl
  command: youtube-dl -U
  register: youtubedl_update_out
  when: youtubedl_bin.stat.exists and youtubedl_update
  changed_when: "'Updated youtube-dl.' in youtubedl_update_out.stdout"
  failed_when: "'ERROR:' in youtubedl_update_out.stdout"
  ignore_errors: true

- name: Copy correct script and setup cronjob (type loader)
  block:
    - name: Copy load.sh
      copy:
        src: load.sh
        dest: /usr/local/bin/load.sh.vault
        owner: wiaf
        group: users
        mode: 0775

    - name: Cron Job
      cron:
        name: perform full download via input.txts
        minute: '*'
        hour: '*'
        weekday: '*'
        user: wiaf
        job: "flock -n /tmp/load.lock -c /usr/local/bin/load.sh >> /var/log/bretterload.log 2>&1"
        cron_file: load
        state: present
  when: type == "loader"

- name: Copy correct script and setup cronjob (type internal)
  block:
    - name: Copy load_transfer_locally.sh
      copy:
        src: load_transfer_locally.sh.vault
        dest: /usr/local/bin/load_transfer_locally.sh
        owner: wiaf
        group: users
        mode: 0775

    - name: Cron Job
      cron:
        name: synch with calth04
        minute: '*'
        hour: '*'
        weekday: '*'
        user: wiaf
        job: "flock -n /tmp/brettertransfer.lock -c /usr/local/bin/load_transfer_locally.sh >> /var/log/bretterload.log 2>&1"
        cron_file: load_transfer_locally
        state: present
  when: type == "internal"