---
name: Molecule CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    ignore-tags:
      - "*"
  schedule:
    - cron: "0 0 1 * *"
jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - cleanup_module
          - default
          - plus
          - stable_push
    steps:
      - name: Check out the codebase
        if: "!(matrix.scenario == 'plus' && github.event.pull_request.head.repo.full_name != github.repository)"
        uses: actions/checkout@v2

      - name: Set up Python 3
        if: "!(matrix.scenario == 'plus' && github.event.pull_request.head.repo.full_name != github.repository)"
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Molecule dependencies
        if: "!(matrix.scenario == 'plus' && github.event.pull_request.head.repo.full_name != github.repository)"
        run: pip3 install -r .github/workflows/requirements_molecule.txt

      - name: Run Molecule tests
        if: "!(matrix.scenario == 'plus' && github.event.pull_request.head.repo.full_name != github.repository)"
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          NGINX_CRT: ${{ secrets.NGINX_CRT }}
          NGINX_KEY: ${{ secrets.NGINX_KEY }}
