---
webserver_apache_name: httpd
webserver_apache_user: apache
webserver_apache_conf_file: /etc/httpd/conf/httpd.conf
webserver_apache_manager: httpd
webserver_apache_site_dir: "/etc/{{ webserver_apache_name }}/conf.d"

webserver_nginx_name: nginx
webserver_nginx_user: nginx
webserver_nginx_conf_file: /etc/nginx/nginx.conf
webserver_nginx_manager: nginx
webserver_nginx_site_dir: "/etc/{{ webserver_nginx_name }}/conf.d"
