---
- name: Main configuration
  register: _mariadb_config_changed
  template:
    src: my.cnf
    dest: "{{ mariadb_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ mariadb_overwrite_global_mycnf }}"
  notify: restart mysql

- name: Set startup settings and start mariadb
  service:
    name: mysql
    state: started
    enabled: true
  when: mariadb_enabled_on_startup 

- name: Start mariadb
  service:
    name: mysql
    state: started

- name: 'Wait for mariadb to be started'
  wait_for:
    port: '{{ mariadb_port }}'
    delay: 3
    timeout: 300