---

- name: Purge all mysql packages
  apt:
    pkg: '{{ item }}'
    state: absent
    purge: true
  when: mysql_reinstall
  ignore_errors: true
  with_items:
    - 'mysql*'
    - 'mariadb*'

- name: Install packages
  package:
    name: "{{ mariadb_packages }}"
    state: present
  tags: mariadb