---

- name: Purge all mysql packages
  apt:
    pkg: '{{ item }}'
    state: absent
    purge: true
  when: mariadb_not_installed
  ignore_errors: true
  with_items:
    - 'mysql*'
    - 'mysql'

- name: Install mariadb keys
  apt_key:
    keyserver: "{{ mariadb_apt_keyserver }}"
    id: "{{ mariadb_apt_keyid }}"
    state: present

- name: Pin mariadb apt repository
  template:
    src: 'mariadb.pref'
    dest: /etc/apt/preferences.d/mariadb.pref
  when: mariadb_pin_repository

- name: Install mariadb apt dependencies
  apt:
    pkg: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: 86400
    allow_unauthenticated: yes
  with_items: '{{mariadb_apt_dependencies}}'

- name: Install MySQL-python pip package
  pip:
    name: "{{ item }}"
    state: present
  with_items: '{{ mariadb_pip_dependencies }}'
  become: yes

- name: Install mariadb apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
    filename: mariadb
  register: mariadb_install_packages
  with_items: '{{mariadb_apt_repositories}}'

- name: Install mariadb server apt packages
  apt:
    pkg: '{{ item }}'
    state: present
    allow_unauthenticated: yes
  with_items: '{{mariadb_apt_packages}}'

# Stop automatically started mariadb on first run and delete ib_logfile
# in case a custom log file size is defined.
- name: Stop mariadb after inital installation (for cleanup)
  when: mariadb_not_installed
  service:
    name: mysql
    state: stopped

- name: Delete default innodb log files
  when: mariadb_not_installed
  file:
    path: '{{ mariadb_datadir }}/ib_logfile[01]'
    state: absent