<<<<<<< HEAD
- name: install prerequirements
  apt:
=======
---
- name: install prerequirements 
  apt: 
>>>>>>> 86a21496cfa0312b7163c658faf714e8ff69f636
    name: "{{ php_prerequirements }}"
    state: present
  when: php_prerequirements

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: hkps://keyserver.ubuntu.com
    id: "{{ item }}"
  with_items:
    - 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C

- name: add additional repos
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main'
    validate_certs: true
    update_cache: true
    state: present

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true
<<<<<<< HEAD

=======
>>>>>>> 86a21496cfa0312b7163c658faf714e8ff69f636
- name: install additional packages
  apt:
    name:
      - php{{ php_version }}-common
      - php{{ php_version }}-cli
      - php{{ php_version }}-fpm
<<<<<<< HEAD
      - php{{ php_version }}-gd
      - php{{ php_version }}-mysql
      - php{{ php_version }}-curl
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
      - php{{ php_version }}-intl
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-redis
      - php{{ php_version }}-bz2
      - php{{ php_version }}-ldap
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-gmp
      - php{{ php_version }}-ctype
      - php{{ php_version }}-imagick
#  php-json is now always active (v8)
#      - php{{ php_version }}-json
#      - php-apcu
#      - php-imagick
      - php-smbclient
      - php-redis
    autoremove: true
    state: latest
  tags: php_mods

- name: configure php
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    force: true
  with_items:
    - { file: 'cli.php.ini',  dest: '{{ php_cli_conf_dir }}/php.ini' }
  notify: restart php-fpm


- name: configure php mysql module
  copy:
    dest: /etc/php/{{ php_version }}/mods-available/pdo_mysql.ini
    content: |
      # configuration for PHP MySQL module
      extension=pdo_mysql.so

      [mysql]
      mysql.allow_local_infile=On
      mysql.allow_persistent=On
      mysql.cache_size=2000
      mysql.max_persistent=-1
      mysql.max_links=-1
      mysql.default_port=
      mysql.default_socket=/var/run/mysqld/mysql.sock
      mysql.default_host=
      mysql.default_user=
      mysql.default_password=
      mysql.connect_timeout=60
      mysql.trace_mode=Off
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
=======
    state: present
  tags: php_mods
>>>>>>> 86a21496cfa0312b7163c658faf714e8ff69f636
