---
- name: install prerequirements 
  apt: 
    name: "{{ php_prerequirements }}"
    state: present
  when: php_prerequirements

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: hkps://keyserver.ubuntu.com
    id: "{{ item }}"
  with_items:
    - 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C

- name: add additional repos
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main'
    validate_certs: true
    update_cache: true
    state: present

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true
- name: install additional packages
  apt:
    name:
      - php{{ php_version }}-common
      - php{{ php_version }}-cli
      - php{{ php_version }}-fpm
    state: present
  tags: php_mods