---
- name: Install sury dependencies
  package:
    name: "{{ pkgs }}"
  vars:
    pkgs:
      - lsb-release
      - ca-certificates
      - apt-transport-https

- name: add ppa:ondrej/php 
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install PHP packages version:{{php_version}}
  apt: 
    name: "{{ packages_php }}"
    state: present