---
- name: restart webserver apache
  service:
    name: "{{ webserver_apache_name }}"
    state: restarted

- name: reload webserver apache
  service:
    name: "{{ webserver_apache_name }}"
    state: reloaded

- name: restart webserver apache2
  service:
    name: "{{ webserver_apache_name }}"
    state: restarted

- name: reload webserver apache2
  service:
    name: "{{ webserver_apache_name }}"
    state: reloaded

- name: restart webserver httpd
  service:
    name: "{{ webserver_apache_name }}"
    state: restarted

- name: reload webserver httpd
  service:
    name: "{{ webserver_apache_name }}"
    state: reloaded

- name: restart webserver nginx
  service:
    name: "{{ webserver_nginx_name }}"
    state: restarted

- name: reload webserver nginx
  service:
    name: "{{ webserver_nginx_name }}"
    state: reloaded

- name: restart webserver none
  debug:
    msg: "No webserver could be detected! Make sure you have a webserver installed!"

- name: reload webserver none
  debug:
    msg: "No webserver could be detected! Make sure you have a webserver installed!"
