
rpi: 
  hosts: 
    calth01: 
      hostname: calth01
      ansible_host: 10.0.0.11
    calth02:
      hostname: calth02
      ansible_host: 10.0.0.12
      partition_timemachine: fdc076e6-98ce-44ca-b081-e3200beeefc2
      partition_kittycastle: edfdc395-7655-47ee-9bcc-07e029d13f26
web:
   hosts: 
    bretterboi.online:
      hostname: bretterboi.online
      ansible_host: 207.180.249.112
      mysql_nextcloud_user: nextcloud_db
      php_version: 7.4
      packages_host:
        - youtube-dl
        - bind9
      network_provider: nm
      network_connection: eth0
      state: up
      type: ethernet
      ip:
        address: 10.0.0.12
        bootproto: static
        broadcast: 10.0.0.255
        netmask: 255.255.255.0
        dnsnameservers: 10.0.0.1 9.9.9.9
        dnssearch: ithaka.local
        mtu: 9000


            
#fallback:
#    hosts:
#      10.0.0.11:
#      10.0.0.12: