ithaka:
  hosts:
    calth01:
      hostname: calth01
      ansible_hostname: calth01
      ansible_host: 10.0.0.11

#    calth02:
#      hostname: calth02
#      ansible_hostname: calth02
#      ansible_host: 10.0.0.21

bretterboi:
  hosts:
    calth03:
      hostname: calth03
      ansible_hostname: calth03
      ansible_host: 62.171.146.19

    calth04:
      hostname: calth04
      ansible_hostname: calth04
      ansible_host: 207.180.249.112

