
rpi: 
  hosts: 
    calth01: 
      hostname: calth01
      ansible_host: 10.0.0.11
    calth02:
      hostname: calth02
      ansible_host: 10.0.0.12
      partition_timemachine: fdc076e6-98ce-44ca-b081-e3200beeefc2
      partition_kittycastle: edfdc395-7655-47ee-9bcc-07e029d13f26
web:
   hosts: 
    calth03:
      hostname: calth03
      ansible_host: 62.171.146.19
    calth04:
      hostname: calth04
      ansible_host: 207.180.249.112
      mysql_nextcloud_user: nextcloud_db
      php_version: 7.4
