---

- name: wrapper playbook for kitchen testing "ansible-mysql-hardening"
  hosts: localhost
  pre_tasks:
    - file: path="/etc/mysql" state=directory
    - name: Copy initctl_faker into place for Ubuntu 14.04.
      copy:
        src: initctl_faker
        dest: /sbin/initctl
        mode: 0755
        force: yes
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'
      changed_when: false
    - name: install procps for debian systems
      apt: name=procps state=installed update_cache=yes
      when: ansible_distribution == 'Debian'
  vars:
    overwrite_global_mycnf: no
    mysql_root_password: iloverandompasswordsbutthiswilldo
    mysql_user_password: iloverandompasswordsbutthiswilldo
    mysql_config_file: /etc/mysql/mariadb.cnf
    mysql_root_password_update: yes
  roles:
    - geerlingguy.mysql
    - ansible-mysql-hardening
