---
- name: Update apt cache
  apt: 
    update_cache: yes 
    cache_valid_time: 86400
  changed_when: false
- name: install prerequirements 
  apt: 
    name: "{{ nextcloud_prerequirements }}"
    state: present
  when: nextcloud_prerequirements

- name: Get nextcloud
  unarchive:
    src: https://download.nextcloud.com/server/releases/nextcloud-"{{nextcloud-version}}".zip
    dest: "{{ nextcloud_setup_dir }}"
    remote_src: true
    mode: 0744

- name: Ensure MySQL users are present
  mysql_user:
    name: "{{ mysql_nextcloud_user }}"
    password: "{{ secure_mysql_nextcloud_password }}"
    priv: "nextcloud.*:ALL"
  no_log: true