packages_host:
  - systemd

samba_shares:
- name: "backups"
  samba_share_path: "/var/backups"
  uuid: "518cc0cc-f129-349d-8b94-cf192ccbb08e"
  owner: "wiaf"
  group: "wiaf"
  folder_perms: "1775"
  fstype: "hfsplus"
  options: "noexec,nodev,noatime,nodiratime"
