packages_host:
  - systemd

php_version:  7.3

samba_shares:
#[]
- name: "kittycastle"
  folder_perms: "0775"
  browsable: "yes"
  fstype: "ext4"
  uuid: "458430dd-aab0-4031-a16c-81786d1dd7d7"
  options: "noexec,nodev,noatime,nodiratime"
  valid_users: "smbuser, wiaf, timemachine"

- name: "music01"
  folder_perms: "0775"
  uuid: "762164b5-663a-4ded-b1fd-c033e82680d9"
  browsable: "yes"
  read_only: "no"
  guest_okay: "no"
  options: "nodev,noatime,nodiratime"