packages_host:
  - systemd

samba_shares:

- name: "kittycastle"
  samba_share_path: "/var/kittycastle"
  uuid: "e42ee214-836e-4884-b02e-15c69f96a033"
  owner: "wiaf"
  group: "wiaf"
  folder_perms: "1775"
  fstype: "ext4"
  options: "defaults"

rclone_version: "1.55.1"
rclone_configs: ""
rclone_arch: "arm"

type: internal

#  - name: Brettercloud
#    properties:
