samba_shares:
#[]
- name: "timemachine"
  samba_share_name: "timemachine"
  samba_mount_path: "/media/timemachine"
  uuid: "2edfdc395-7655-47ee-9bcc-07e029d13f26"

- name: "kittycastle"
  browsable: "yes"
  folder_perms: "0775"
  samba_share_name: "kittycastle"
  samba_mount_path: "/media/kittycastle"
  uuid: "fdc076e6-98ce-44ca-b081-e3200beeefc2"
  #options: "rw,seclabel,relatime,attr2,inode64,noquota" 

- name: "music01"
  samba_share_name: "music01"
  samba_mount_path: "/media/music01"
  uuid: "762164b5-663a-4ded-b1fd-c033e82680d9"
  browsable: "yes"
  read_only: "no"
  guest_okay: "no"
