---

- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: true

- name: Add Nginx Config
  copy: 
    src: nginx.conf 
    dest: /etc/nginx/sites-available/default


- name: enable default configuration
  file: 
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default 
    state: link

- name: copy index.html
  template: 
    src: templates/index.html.j2 
    dest: /usr/share/nginx/html/index.html
    mode: 0644