---

- hosts: bretterboi
  roles:
  - common

- hosts: calth03
  roles:
    - { role: php, tags: [ "php" ] }
    - { role: nginx, tags: [ "nxing" ] }

- hosts: calth04
  roles:
   - { role: snapd, tags: [ "snapd" ] }
   - { role: "youtube-dl", tags: [ "youtube-dl" ] }