---

- hosts: bretterboi
  roles:
  - common

- hosts: calth03
  roles:
    - { role: nginx, tags: [ "nginx" ] }
    - { role: php, tags: [ "php" ] }
    - { role: wordpress, tags: [ "nginx" ] }

- hosts: calth04
  roles:
   - { role: snapd, tags: [ "snapd" ] }
   - { role: youtube-dl, tags: [ "youtube-dl" ] }
   - { role: rsyslog, tags: [ "rsyslog" ] }
