---

- hosts: calth03
  gather_facts: yes
  tasks:
    - debug: var=ansible_hostname
  roles:
<<<<<<< HEAD
   - role: php
   - role: nginx
  #ignore_errors: true
=======
  # - role: common
   - role: lemp_u1804

  #ignore_errors: true
>>>>>>> master
