---

- hosts: calth03
  gather_facts: yes
  roles:
   - role: mariadb
     tags: mariadb
   - role: nginx
     tags: nginx
   - role: php
     tags: php
   - role: wordpress
     tags: wordpress
  ignore_errors: true
