---
#- hosts: ithaka
#  roles:
#   - common
#  gather_facts: no
#  become: yes

- hosts: calth01
  roles:
   - { role: raspi-config, tags: [ "raspi-config" ] }
   - { role: hdparm, tags: [ "hdparm" ] }
   - { role: pihole, tags: [ "pihole" ] }
   - { role: ansible-rclone, tags: [ "rclone" ] }

- hosts: calth02
  roles:
   - { role: raspi-config, tags: [ "raspi-config" ] }
   - { role: hdparm, tags: [ "hdparm" ] }
   - { role: samba, tags: [ "samba" ] }
   - { role: ansible-rclone, tags: [ "rclone" ] }
   - { role: yotube-dl, tags: [ "yotube-dl" ] }
   - { role: rsyslog, tags: [ "rsyslog" ] }
