---

- hosts: all
#  tasks:
#    - debug: var=ansible_hostname

- name: Run all prod environment
  import_playbook: common.yml

- name: Run on calth01 
  import_playbook: calth01.yml

- name: Run on calth02
  import_playbook: calth02.yml

- name: Run on bretterboi.online
  import_playbook: bretterboi.online.yml
  