---
# Fail2Ban
- include_tasks: fail2ban.yml
  when: security_fail2ban_enabled | bool

- include_tasks: autoupdate-Debian.yml
  when:
    - ansible_os_family == 'Debian'
    - security_autoupdate_enabled | bool