---

- name: install samba
  apt:
    name: "{{ samba_prerequirements }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: create_shares | creating shared directories
  file:
    path: "{{ samba_share_path + '/' + item['name'] }}"
    owner: "{{ item['owner']|default(omit) }}"
    group: "{{ item['group']|default(omit) }}"
    mode: "{{ item['folder_perms'] }}"
    state: directory
  become: true
  with_items: "{{ samba_shares }}"
  when: samba_shares is defined

- name: Mount devices to shares
  mount:
    path: "{{ samba_share_path + '/' + item['name'] }}"
    src: UUID="{{ item['uuid'] }}"
    fstype: "{{ item['fstype'] }}"
    opts: "{{ item['options'] }}"
    state: mounted
  with_items: "{{ samba_shares }}"
  notify:
  - restart smbd
  - restart nmbd
  ignore_errors: yes
  when: samba_shares is defined

- name: samba_users | creating samba user passwords
  shell: "(echo {{ item['smbpasswd'] }}; echo {{ item['smbpasswd'] }}) | smbpasswd -s -a {{ item['name'] }}"
  become: true
  no_log: true
  with_items: "{{ samba_users }}"
