---

- name: install samba
  apt:
    name: "{{ samba_prerequirements }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: samba_groups | ensuring groups exist
  group:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ samba_groups }}"
  when: samba_groups is defined

- name: create_shares | creating shared directories
  file:
    path: "{{ samba_share_path + '/' + item['name'] }}"
    owner: "{{ item['owner']|default(omit) }}"
    group: "{{ item['group']|default(omit) }}"
    mode: "{{ item['folder_perms'] }}"
    state: directory
  become: true
  with_items: "{{ samba_shares }}"

- include_tasks: samba_users.yml
  when: samba_users is defined

- include_tasks: create_shares.yml
  when: samba_shares is defined

- include: config_samba.yml