---
- name: Deploy userscripts
  copy:
    src: files/
    dest: /usr/local/bin/
    mode: +x
    force: yes
  become: yes
  tags: common_config

- name: copying smb.conf
  become: true
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644

- name: create and mount folders
  block:

    - name: create_shares | creating shared directories
      file:
        path: "{{ samba_share_path + '/' + item['name'] }}"
        owner: "{{ item['owner']|default(omit) }}"
        group: "{{ item['group']|default(omit) }}"
        mode: "{{ item['folder_perms'] }}"
        state: directory
      become: true
      with_items: "{{ samba_shares }}"

    - name: Mount samba shares
      mount:
        path: "{{ samba_share_path + '/' + item['name'] }}"
        src: UUID="{{ item['uuid'] }}"
        fstype: "{{ item['fstype'] }}"
        opts: "{{ item['options'] }}"
        state: mounted
      with_items: "{{ samba_shares }}"
      notify:
      - restart smbd
      - restart nmbd
      ignore_errors: yes
      when: samba_shares is defined

    - name: samba_users | creating samba user passwords
      shell: "(echo {{ item['smbpasswd'] }}; echo {{ item['smbpasswd'] }}) | smbpasswd -s -a {{ item['name'] }}"
      become: true
      no_log: true
      with_items: "{{ samba_users }}"