---
mariadb_version: '10.3'

mariadb_apt_keyserver: 'keyserver.ubuntu.com'
mariadb_apt_keyid: '0xF1656F24C74CD1D8'
mariadb_apt_mirror: 'http://ftp.hosteurope.de'
mariadb_apt_repositories:
  - 'deb [arch=amd64,i386,ppc64el] {{ mariadb_apt_mirror }}/mirror/mariadb.org/repo/{{ mariadb_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main'
  - 'deb-src {{ mariadb_apt_mirror }}/mirror/mariadb.org/repo/{{ mariadb_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main'

mariadb_pin_repository: true
mariadb_overwrite_global_mycnf: true

mysql_packages:
 - mariadb-server
 - mariadb-client

mysql_python_package_debian:
  - python-mysqldb
  - python-openssl
  - python3-pip

mariadb_apt_tools_packages:
  - mysqltuner
  - percona-toolkit

mysql_daemon: mysql
mariadb_enabled_on_startup: yes

mariadb_config_file: /etc/mysql/my.cnf
mysql_datadir: /var/lib/mysql
mariadb_socket: /var/run/mysqld/mysqld.sock

mariadb_admin_home: '/root'
mariadb_admin_user: 'admin'

mariadb_default_hosts:
  - localhost
  - 127.0.0.1
  - ::1

# Logging settings.
mariadb_log: ""
mariadb_log_error: /var/log/mysql.err
mariadb_syslog_tag: mysql


mariadb_config_include_files: []
#  - src: path/relative/to/playbook/file.cnf
#  - { src: path/relative/to/playbook/anotherfile.cnf, force: yes }


# MySQL connection settings.
mariadb_port: "3306"
mariadb_bind_address: '0.0.0.0'
mariadb_datadir: /var/lib/mysql
mariadb_pid_file: /var/run/mysqld/mysqld.pid

# Memory settings (default values optimized ~512MB RAM).
mariadb_key_buffer_size: "256M"
mariadb_max_allowed_packet: "128M"
mariadb_table_open_cache: "256"
mariadb_sort_buffer_size: "1M"
mariadb_read_buffer_size: "1M"
mariadb_read_rnd_buffer_size: "4M"
mariadb_myisam_sort_buffer_size: "64M"
mariadb_table_cache: 2000
mariadb_thread_cache_size: "8"
mariadb_query_cache_size: "16M"
mariadb_max_connections: 151
mariadb_tmp_table_size: '64M'
mariadb_max_heap_table_size: '64M'
mariadb_join_buffer_size: '3M'

# Other settings.
mariadb_wait_timeout: 1800
mariadb_net_read_timeout: 120
mariadb_skip_name_resolve: true
mariadb_back_log: 100
mariadb_max_connect_errors: 10000
mariadb_open_files_limit: 20000
mariadb_interactive_timeout: 3600
mariadb_connect_timeout: 120

# InnoDB settings.
# Set .._buffer_pool_size up to 80% of RAM but beware of setting too high.
mariadb_innodb_file_per_table: "1"
mariadb_innodb_buffer_pool_size: "256M"
# Set .._log_file_size to 25% of buffer pool size.
mariadb_innodb_log_file_size: "64M"
mariadb_innodb_log_buffer_size: "8M"
mariadb_innodb_flush_log_at_trx_commit: "2"
mariadb_innodb_lock_wait_timeout: 600
mariadb_innodb_additional_mem_pool_size: "8M"

# mysqldump settings.
mariadb_mysqldump_max_allowed_packet: "64M"